export const data = [
  {
    id: 1,
    topic: "General",
    level: "junior",
    number: "01",
    question: "What HTTP download methods do you know?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "https://developer.mozilla.org/ru/docs/Web/HTTP/Methods",
  },
  {
    id: 2,
    topic: "General",
    level: "junior",
    number: "02",
    question: "What versions of the HTTP protocol do you have?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "https://developer.mozilla.org/ru/docs/Web/HTTP/Overview",
  },
  {
    id: 3,
    topic: "General",
    level: "junior",
    number: "03",
    question: "How to find out remote (future) HTTP codes?",
    questionCode: [],
    answerQuestion: [
      "https://upload.wikimedia.org/wikipedia/commons/6/65/Http-headers-status.gif",
    ],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 4,
    topic: "General",
    level: "junior",
    number: "04",
    question:
      "What is the joint use of resources between sources? How to fix problems with CORS?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "https://developer.mozilla.org/ru/docs/Web/HTTP/CORS",
  },
  {
    id: 5,
    topic: "General",
    level: "junior",
    number: "05",
    question: "What is a cookie?",
    questionCode: [],
    answerQuestion: [
      "https://ru.wikipedia.org/wiki/Cookie",
      "https://policies.google.com/technologies/cookies?hl=ru",
    ],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 6,
    topic: "General",
    level: "junior",
    number: "06",
    question: "What is the maximum cookie size?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 7,
    topic: "General",
    level: "junior",
    number: "07",
    question: "What does the use strict directive mean?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks:
      "https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Strict_mode",
  },
  {
    id: 8,
    topic: "General",
    level: "junior",
    number: "08",
    question: "How does JS differ when working on the front-end and back-end?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 9,
    topic: "General",
    level: "junior",
    number: "09",
    question: "What are static and dynamic typing?",
    questionCode: [],
    answerQuestion: [
      "https://senior.ua/articles/kak-ponyat-raznicu-mezhdu-staticheskoy-i-dinamicheskoy-tipizaciey",
    ],
    nswerCode: [],
    answerLinks: "https://ru.reactjs.org/docs/state-and-lifecycle.html",
  },
  {
    id: 10,
    topic: "General",
    level: "junior",
    number: "10",
    question: "How does the client interact with the server?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 11,
    topic: "General",
    level: "junior",
    number: "11",
    question: "What is REST?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 12,
    topic: "General",
    level: "junior",
    number: "12",
    question:
      "Explain the concept of mutability / immutability? What types are mutable and vice versa?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks:
      "https://blog.logrocket.com/what-are-react-pure-functional-components/#:~:text=PureComponent%20class%20are%20treated%20as,comparison%20for%20props%20and%20state.",
  },
  {
    id: 13,
    topic: "General",
    level: "junior",
    number: "13",
    question: "How to look for errors in the code? Are you using a debugger?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "https://redux.js.org/usage/deriving-data-selectors",
  },
  {
    id: 14,
    topic: "General",
    level: "junior",
    number: "14",
    question: "What famous people from the JS world do you know?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "https://redux.js.org/usage/deriving-data-selectors",
  },
];

export default data;
