export const data = [
  {
    id: 1,
    topic: "React",
    level: "junior",
    number: "01",
    question: "Did you work with class components? What is their specialty?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 2,
    topic: "React",
    level: "junior",
    number: "02",
    question:
      "Which data is better to store in the state of the component, and which to pass through props? Give an example.",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 3,
    topic: "React",
    level: "junior",
    number: "03",
    question:
      "Are you familiar with hooks? What are their advantages? Did you have to do your own and for what purpose?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 4,
    topic: "React",
    level: "junior",
    number: "04",
    question:
      "Are you familiar with fragments and portals? Why are they needed?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 5,
    topic: "React",
    level: "junior",
    number: "05",
    question: "When and what are refs used for?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 6,
    topic: "React",
    level: "junior",
    number: "06",
    question: "What methods of component life cycle do you know7",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 7,
    topic: "React",
    level: "junior",
    number: "07",
    question:
      "Are you familiar with hooks? What are their advantages? Did you have to do your own and for what purpose?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 8,
    topic: "React",
    level: "junior",
    number: "08",
    question:
      "Are you familiar with fragments and portals? Why are they needed?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 9,
    topic: "React",
    level: "junior",
    number: "09",
    question: "What methods of component life cycle do you know?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "https://ru.reactjs.org/docs/state-and-lifecycle.html",
  },
  {
    id: 10,
    topic: "React",
    level: "junior",
    number: "10",
    question:
      "In which method of the life cycle of the component is it better to make requests to the server? Why?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 11,
    topic: "React",
    level: "junior",
    number: "11",
    question: "Was there experience with context? When should I use it?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 12,
    topic: "React",
    level: "junior",
    number: "12",
    question: "What is special about PureComponent?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks:
      "https://blog.logrocket.com/what-are-react-pure-functional-components/#:~:text=PureComponent%20class%20are%20treated%20as,comparison%20for%20props%20and%20state.",
  },
  {
    id: 13,
    topic: "React",
    level: "junior",
    number: "13",
    question:
      "Did it work with memoized selectors? What are they used for and what is the principle of operation?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "https://redux.js.org/usage/deriving-data-selectors",
  },
  {
    id: 14,
    topic: "React",
    level: "junior",
    number: "14",
    question: "What do you see as the advantages of the React librar14",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 15,
    topic: "React",
    level: "junior",
    number: "15",
    question:
      "Why is the React library fast? What are Virtual DOM and Shadow DOM?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "https://ru.reactjs.org/docs/faq-internals.html",
  },
  {
    id: 16,
    topic: "React",
    level: "junior",
    number: "16",
    question:
      "Why are keys in lists? Is it possible to make the indexes of the array elements as keys? When is it justified?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 17,
    topic: "React",
    level: "junior",
    number: "17",
    question: "What is the main idea of Redux?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "https://highload.today/redux-react/",
  },
  {
    id: 18,
    topic: "React",
    level: "junior",
    number: "18",
    question: "Working with styles in React.",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "https://ru.reactjs.org/docs/faq-styling.html",
  },
  {
    id: 19,
    topic: "React",
    level: "junior",
    number: "19",
    question:
      "Is React a library or a framework? What is the difference between these two concepts.",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 20,
    topic: "React",
    level: "junior",
    number: "20",
    question: "Can jQuery be used with React? Why yes / no?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 21,
    topic: "React",
    level: "junior",
    number: "21",
    question: "What is codemod?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks:
      "https://blog.logrocket.com/how-to-use-codemod-to-upgrade-your-react-version/",
  },
  {
    id: 22,
    topic: "React",
    level: "junior",
    number: "22",
    question:
      "Have you ever had to configure a React project from scratch? What tools did you use to do this?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 23,
    topic: "React",
    level: "junior",
    number: "23",
    question: "List all the libraries you used in connection with React.",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
  {
    id: 24,
    topic: "React",
    level: "junior",
    number: "24",
    question:
      "What was the most difficult thing you had to implement using React?",
    questionCode: [],
    answerQuestion: [],
    nswerCode: [],
    answerLinks: "",
  },
];

export default data;
